working_directory = "Documents/Projects/"

[window]
padding = { y = 30, x = 10 }
dimensions = {columns = 200, lines = 85}
dynamic_padding = true
dynamic_title = false
decorations = "Transparent"
blur = true
opacity = 0.85
startup_mode = "Maximized"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
